### ISSUE TITLE
FileNotFoundError ([Errno 2] No such file or directory: '~/cltk/stop/french/frenchtexts.txt')

### ISSUE THREAD

**Issue by nat1881** [nat1881/cltk#9]
in stop.french.frequencies 
Not sure why this has stopped working, because as far as I can see the file is still there

**Comment by mlj** [comment]
I don't know the directory layout you use on your own computer. But it looks like you're missing a directory level, so `~/cltk/cltk/stop/french/frenchtexts.txt` instead of `~/cltk/stop/french/frenchtexts.txt` in
https://github.com/nat1881/cltk/blob/french/cltk/stop/french/frequencies.py#L11

But you're going to have to find a different way of doing this. Hardcoding the path will not work. Think of what happens when cltk is installed via pip, for example.

**Comment by mlj** [comment]
Here's a hint: https://stackoverflow.com/a/7783326

**Comment by nat1881** [comment]
Thank you!

**Comment by nat1881** [comment]
I'm actually wondering whether the file should be there at all, looking at the other stop files which link to external rather than internal lists

**Comment by mlj** [comment]
I don't know. The data-code split in CLTK often confuses me. @diyclassics?

**Comment by diyclassics** [comment]
Fwiw I have been revising the Stops module this summer, so I have some perspective on this. And, yes, @mlj, the data-code split needs to be handled better.

But for this specific instance, here is my recommendation:
1. Put the output of this script, i.e. the stoplight itself, in a file called stops.py or something similar as a Python list. So, for example: STOPS_LIST = ['le', 'la', 'un', etc.] It looks like you have already done this.

2. Keep the txt file in this directory now for reference.

3. At the top of stops.py, add the code you used to create the list in comments at the top of the file. So, for example:

```
### word_tokenizer = WordTokenizer('french')
### words = word_tokenizer.tokenize(file_content)
### fdist = FreqDist(words)
### etc.
```
And be sure to include the source file for your output, i.e. frenchtexts.txt

4. Remove frequencies.py

This way everything is documented (and working) and the purpose of the module as it is now written, i.e. access to a stoplist, is maintained.

PJB

**Comment by nat1881** [comment]
Great, thank you - I'll do that!
